# config.yaml
TOKEN: "YOUR_TOKEN_HERE"              # Discord bot token, string
CHANNEL_ID: 123456789012345678        # Channel ID for bot to listen in, integer
ADMIN_CHANNEL_ID: 987654321098765432  # Channel ID of channel for administrator login (Player name, Message, no autodeletion), integer


# OPTIONAL !!!! Change flatfile storage to SQL based database:
USE_DATABASE: false                   # Change to "true" to enable Database Storage, set to "false" to switch to flatfile storage. Default value: false, Boolean
DATABASE:
  HOST: "localhost"                   # Location of database server, string
  PORT: 3306                          # Port database is listening on, integer
  USER: "your_username"               # username in database with access to database defined in DATABASE_NAME, string
  PASSWORD: "your_password"           # Password to USER account, string
  DATABASE_NAME: "RADIO_BOT"          # Database name, default: RADIO_BOT, string